# Generated by Django 3.1.5 on 2021-01-31 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=50)),
                ('s_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender'), ('A', 'All')], max_length=1)),
                ('s_type', models.CharField(choices=[('GOV', 'Government'), ('PVT', 'Private'), ('INT', 'International')], max_length=3)),
                ('s_eligibility', models.CharField(choices=[('Merit', 'Merit Based'), ('Income Based', 'Income Based'), ('Educational Qualification', 'Educational Qualification'), ('Other', 'Other')], max_length=50)),
                ('s_country', models.CharField(choices=[('India', 'India'), ('Study Abroad', 'Study Abroad')], max_length=50)),
                ('s_content', models.TextField(max_length=5000)),
                ('s_award', models.CharField(max_length=50)),
                ('s_start', models.CharField(max_length=50)),
                ('s_stop', models.CharField(max_length=50)),
                ('s_class', models.ManyToManyField(to='scholarships.Class')),
                ('s_course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scholarships.course')),
                ('s_religion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scholarships.religion')),
                ('s_state', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scholarships.state')),
            ],
        ),
    ]
