# Generated by Django 3.1.5 on 2021-02-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0003_auto_20210201_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='s_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
