# Generated by Django 3.1.5 on 2021-02-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0004_scholarship_s_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='s_category',
            field=models.CharField(blank=True, choices=[('SC/ST/OBC', 'SC/ST/OBC'), ('Minority', 'Minority'), ('Physically Disabled', 'Physically Disabled'), ('Others', 'Others')], max_length=50, null=True),
        ),
    ]
