# Generated by Django 3.1.5 on 2021-02-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0005_auto_20210201_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='s_about',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='s_type',
            field=models.CharField(choices=[('Government', 'Government'), ('Private', 'Private'), ('International', 'International')], max_length=20),
        ),
    ]
