# Generated by Django 3.1.5 on 2021-02-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0006_auto_20210201_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='s_stop',
            new_name='s_deadline',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='s_start',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='s_updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='s_award',
            field=models.CharField(max_length=150),
        ),
    ]
