# Generated by Django 3.1.5 on 2021-02-01 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0007_auto_20210201_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='cl_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='co_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='religion',
            old_name='r_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='s_about',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='s_award',
            new_name='award',
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='s_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='s_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='s_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='s_course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='s_deadline',
            new_name='deadline',
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='s_eligibility',
            new_name='eligibility',
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='s_gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='s_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='s_religion',
            new_name='religion',
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='s_class',
            new_name='sclass',
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='s_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='s_type',
            new_name='stype',
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='s_updated_on',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='st_name',
            new_name='name',
        ),
    ]
