# Generated by Django 3.1.5 on 2021-02-02 14:06

from django.db import migrations, models
import scholarships.models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0008_auto_20210202_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=scholarships.models.upload_location),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
