# Generated by Django 3.1.5 on 2021-02-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0009_auto_20210202_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='site_url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
