# Generated by Django 3.1.5 on 2021-02-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0011_scholarship_date_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='date_test',
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
