# Generated by Django 3.1.5 on 2021-02-02 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0013_auto_20210203_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='name',
            new_name='title',
        ),
    ]
