# Generated by Django 3.1.5 on 2021-02-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0015_auto_20210203_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
    ]
