# Generated by Django 3.1.5 on 2021-02-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0016_auto_20210203_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='gender',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='gender',
            field=models.ManyToManyField(to='scholarships.Gender'),
        ),
    ]
