# Generated by Django 3.1.5 on 2021-02-16 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0019_bookbank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookbank',
        ),
    ]
