# Generated by Django 3.1.5 on 2021-03-19 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0021_auto_20210216_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='award',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='content',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scholarships.country'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scholarships.course'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='eligibility',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='gender',
            field=models.ManyToManyField(blank=True, null=True, to='scholarships.Gender'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scholarships.religion'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='sclass',
            field=models.ManyToManyField(blank=True, null=True, to='scholarships.Class'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scholarships.state'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scholarships.category'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='stype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scholarships.type'),
        ),
    ]
