# Generated by Django 3.1.5 on 2021-03-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0022_auto_20210320_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='gender',
            field=models.ManyToManyField(to='scholarships.Gender'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='sclass',
            field=models.ManyToManyField(to='scholarships.Class'),
        ),
    ]
