# Generated by Django 3.1.5 on 2021-03-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0023_auto_20210320_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='contact',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='deadline',
            field=models.DateField(),
        ),
    ]
