# Generated by Django 3.1.5 on 2021-03-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0024_auto_20210330_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='award',
            field=models.CharField(max_length=150),
        ),
    ]
