# Generated by Django 3.1.5 on 2021-05-13 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Country'},
        ),
        migrations.AlterModelOptions(
            name='crowdsource',
            options={'verbose_name_plural': 'CrowdSource'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name_plural': 'District'},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name_plural': 'Loan'},
        ),
        migrations.AlterModelOptions(
            name='loanamt',
            options={'verbose_name_plural': 'LoanAmt'},
        ),
        migrations.AlterModelOptions(
            name='religion',
            options={'verbose_name_plural': 'Religion'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name_plural': 'State'},
        ),
    ]
