# Generated by Django 3.1.5 on 2021-05-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_auto_20210513_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdsource',
            name='reviewed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
