# Generated by Django 3.1.5 on 2021-05-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookbanks', '0002_auto_20210513_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdsource',
            name='reviewed',
            field=models.BooleanField(blank=True, default='No', null=True),
        ),
    ]
